/* begin copyright text
 *
 * Copyright © 2016 PTC Inc., Its Subsidiary Companies, and /or its Partners. All Rights Reserved.
 *
 * end copyright text
 */'use strict';var i18nextOptions={debug:/* isRoot */ /* isRoot */!1/* store in local storage */,fallbackLng:"en",backend:{loadPath:"locales/__lng__/__ns__.json",parse:function(data){data=data.replace(/\/\/(.*)$/gm,"");//Remove double slash comments
return JSON.parse(data)}},ns:["translation"],interpolation:{suffix:"__",prefix:"__"},fallbackNS:"translation",load:"all"};let langOverride;if(0<=window.top.location.search.indexOf("pseudo")){langOverride="qps";i18nextOptions.preload=["qps"]}else if(0>window.top.location.search.indexOf("lng")){langOverride=localStorage.getItem("userLang");i18nextOptions.preload=[langOverride]}if(langOverride){i18nextOptions.lng=langOverride;document.cookie=`i18next=${langOverride}`}else{i18nextOptions.detection={order:["querystring","navigator"],caches:["cookie"]}}const init=function(){window.i18next.use(window.i18nextXHRBackend);window.i18next.use(window.i18nextBrowserLanguageDetector);window.i18next.init(i18nextOptions).then(()=>{window.i18nextLoaded=/* isRoot */!0/*session only*/ /* store in memory only */ /* store filter in memory only */ /* skip dispatch */ /* skip pause/reset of video time */;document.body.dispatchEvent(new CustomEvent("i18nextLoaded"))}).catch(console.error)};if(window.i18next){init()}else{setTimeout(init,10)}/**
 * @returns help center URL for user's current lang, or if current lang is unsupported defaults to en
 */window.getHelpCenterURL=()=>{const supportedHelpCenterLangs=["en","es","fr","it","ja","de","ko","zh_CN","zh_TW"];let lang=window.i18next.language&&window.i18next.language.split("-")[0];//get the language code out of the IETF tag
if("zh"===lang){lang=window.i18next.language.replace("-","_")}// fallback to the en language if there's no Help Center language site for the i18next language
if(!supportedHelpCenterLangs.includes(lang)){lang="en"}return"https://support.ptc.com/help/vuforia/editor/"+lang};